"""
Tests for data generator quality, correctness, and reader compatibility.

Philosophy:
  Tests must validate CORRECT behaviour, not just confirm that code runs.
  A test that always passes regardless of the implementation is worse than
  no test — it creates false confidence.

Test groups:

1. **Unit tests** — no MPI, no file I/O.
   * ``gen_random_tensor`` seed reproducibility, uniqueness, and entropy.
   * ``DataGenerator`` class constants and static helpers.
   * RNG flow-through (same rng object → different output each call).

2. **Format correctness** — generate files, open them with the native library
   and verify *structural* correctness (dtype, shape, keys, schema).

3. **Data uniqueness** — generated files must contain non-identical data both
   *across* files and *within* a file (sample-to-sample).

4. **Reader compatibility** — files generated by each generator must be opened
   and parsed correctly by the matching DLIO reader class.

5. **Reproduciblity** — the same configuration must produce bit-identical files
   on successive runs.

6. **Entropy / non-compressibility** — generated data must be high-entropy and
   resistant to trivial compression (validates dgen-py or uniform-RNG output).
"""

import hashlib
import io
import os
import pathlib
import shutil
import logging
import zlib

import numpy as np
import pytest

logging.basicConfig(
    level=logging.INFO,
    handlers=[logging.StreamHandler()],
    format='[%(levelname)s] %(message)s',
)

# ─── Module-level imports (no MPI required) ──────────────────────────────────
from dlio_benchmark.utils.utility import gen_random_tensor
from dlio_benchmark.data_generator.data_generator import DataGenerator

# ─── Test infrastructure ─────────────────────────────────────────────────────
from hydra import initialize_config_dir, compose
from omegaconf import OmegaConf
from mpi4py import MPI
from dlio_benchmark.utils.config import ConfigArguments
from dlio_benchmark.utils.utility import DLIOMPI
from dlio_benchmark.main import DLIOBenchmark
import dlio_benchmark

comm = MPI.COMM_WORLD
config_dir = os.path.dirname(dlio_benchmark.__file__) + "/configs/"
DLIO_TEST_OUTPUT_DIR = os.environ.get("DLIO_TEST_OUTPUT_DIR", "dlio_test_output")

from tests.utils import TEST_TIMEOUT_SECONDS


def init():
    DLIOMPI.get_instance().initialize()


def finalize():
    from dlio_benchmark.checkpointing.pytorch_checkpointing import PyTorchCheckpointing
    from dlio_benchmark.checkpointing.tf_checkpointing import TFCheckpointing
    from dlio_benchmark.checkpointing.pytorch_obj_store_checkpointing import PyTorchObjStoreCheckpointing
    from dlio_benchmark.framework.torch_framework import TorchFramework
    from dlio_benchmark.framework.tf_framework import TFFramework
    PyTorchCheckpointing._PyTorchCheckpointing__instance = None
    TFCheckpointing._TFCheckpointing__instance = None
    PyTorchObjStoreCheckpointing._PyTorchObjStoreCheckpointing__instance = None
    TorchFramework._TorchFramework__instance = None
    TFFramework._TFFramework__instance = None
    DLIOMPI.reset()


def clean(storage_root="./"):
    comm.Barrier()
    if comm.rank == 0:
        shutil.rmtree(os.path.join(storage_root, "checkpoints"), ignore_errors=True)
        shutil.rmtree(os.path.join(storage_root, "data/"), ignore_errors=True)
        shutil.rmtree(os.path.join(storage_root, DLIO_TEST_OUTPUT_DIR), ignore_errors=True)
    comm.Barrier()


def run_benchmark(cfg, storage_root="./", verify=True):
    comm.Barrier()
    if comm.rank == 0:
        shutil.rmtree(os.path.join(storage_root, DLIO_TEST_OUTPUT_DIR), ignore_errors=True)
    comm.Barrier()
    ConfigArguments.reset()
    workload_dict = OmegaConf.to_container(cfg["workload"], resolve=True)
    workload_dict.setdefault("output", {})["folder"] = DLIO_TEST_OUTPUT_DIR
    benchmark = DLIOBenchmark(workload_dict)
    benchmark.initialize()
    benchmark.run()
    benchmark.finalize()
    if comm.rank == 0 and verify:
        import glob
        output_pattern = os.path.join(benchmark.output_folder, "*_output.json")
        assert len(glob.glob(output_pattern)) == benchmark.comm_size
    return benchmark


def _sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _find_files(cfg, benchmark, ext):
    """Return (train_files, valid_files) sorted lists for a given extension."""
    data_folder = cfg.workload.dataset.data_folder
    train = sorted(pathlib.Path(f"{data_folder}/train").rglob(f"*.{ext}"))
    valid = sorted(pathlib.Path(f"{data_folder}/valid").rglob(f"*.{ext}"))
    return train, valid


# ═══════════════════════════════════════════════════════════════════════════
# 1.  Unit tests — gen_random_tensor properties
# ═══════════════════════════════════════════════════════════════════════════

def test_gen_random_tensor_seed_reproducibility():
    """Same seed must produce byte-identical arrays on every call."""
    arr1 = gen_random_tensor(shape=(64, 64), dtype=np.float32, seed=42)
    arr2 = gen_random_tensor(shape=(64, 64), dtype=np.float32, seed=42)
    np.testing.assert_array_equal(arr1, arr2,
        err_msg="gen_random_tensor with same seed produced different arrays")


def test_gen_random_tensor_seed_uniqueness():
    """Different seeds must produce different arrays."""
    arr0 = gen_random_tensor(shape=(128,), dtype=np.float32, seed=10)
    arr1 = gen_random_tensor(shape=(128,), dtype=np.float32, seed=11)
    assert not np.array_equal(arr0, arr1), (
        "Seeds 10 and 11 produced identical arrays — seeding logic is broken")


def test_gen_random_tensor_no_seed_entropy():
    """Two entropy-seeded calls must produce different arrays."""
    arr1 = gen_random_tensor(shape=(128,), dtype=np.float32, seed=None)
    arr2 = gen_random_tensor(shape=(128,), dtype=np.float32, seed=None)
    assert not np.array_equal(arr1, arr2), (
        "Entropy-seeded gen_random_tensor produced identical arrays — "
        "entropy seeding may be broken")


def test_gen_random_tensor_rng_flow_through():
    """Passing the same rng object must yield different data each call (flow-through)."""
    rng = np.random.default_rng(seed=99)
    arr1 = gen_random_tensor(shape=(256,), dtype=np.float32, rng=rng)
    arr2 = gen_random_tensor(shape=(256,), dtype=np.float32, rng=rng)
    assert not np.array_equal(arr1, arr2), (
        "Passing the same rng twice produced identical arrays — "
        "flow-through is not advancing the RNG state")


def test_gen_random_tensor_rng_reproducibility():
    """Two rngs with the same seed must produce the same sequence."""
    rng_a = np.random.default_rng(seed=7)
    rng_b = np.random.default_rng(seed=7)
    a1 = gen_random_tensor(shape=(128,), dtype=np.float32, rng=rng_a)
    a2 = gen_random_tensor(shape=(128,), dtype=np.float32, rng=rng_a)
    b1 = gen_random_tensor(shape=(128,), dtype=np.float32, rng=rng_b)
    b2 = gen_random_tensor(shape=(128,), dtype=np.float32, rng=rng_b)
    np.testing.assert_array_equal(a1, b1, err_msg="First call differed with same seed")
    np.testing.assert_array_equal(a2, b2, err_msg="Second call differed with same seed")


def test_gen_random_tensor_mpi_rank_seeds_differ():
    """Simulated per-rank seeds must produce statistically distinct arrays."""
    BASE_SEED = DataGenerator.BASE_SEED
    rank0 = gen_random_tensor(shape=(128,), dtype=np.float32, seed=BASE_SEED + 0)
    rank1 = gen_random_tensor(shape=(128,), dtype=np.float32, seed=BASE_SEED + 1)
    assert not np.array_equal(rank0, rank1), (
        "BASE_SEED+0 and BASE_SEED+1 produced identical arrays")


def test_gen_random_tensor_integer_dtype():
    """Seeds must work for integer dtypes."""
    arr1 = gen_random_tensor(shape=(256,), dtype=np.uint8, seed=77)
    arr2 = gen_random_tensor(shape=(256,), dtype=np.uint8, seed=77)
    np.testing.assert_array_equal(arr1, arr2)


def test_gen_random_tensor_data_entropy():
    """Generated data must have high entropy — zlib cannot compress it below 95%."""
    data = gen_random_tensor(shape=(65536,), dtype=np.uint8, seed=42)
    raw = data.tobytes()
    compressed = zlib.compress(raw, level=9)
    ratio = len(compressed) / len(raw)
    assert ratio > 0.95, (
        f"Generated data compressed to {ratio:.1%} — entropy is suspiciously low. "
        "dgen-py or NumPy RNG output should be near-incompressible.")


# ─── DataGenerator class-level helpers ────────────────────────────────────────

def test_base_seed_constant():
    """BASE_SEED must equal 10."""
    assert DataGenerator.BASE_SEED == 10, (
        f"Expected BASE_SEED == 10, got {DataGenerator.BASE_SEED}")


def test_extract_dims_scalar():
    dim = [64, 32, 128, 256]
    raw, d1, d2 = DataGenerator._extract_dims(dim, i=0)
    assert raw == 64 and d1 == 64 and d2 == 32
    raw, d1, d2 = DataGenerator._extract_dims(dim, i=1)
    assert raw == 128 and d1 == 128 and d2 == 256


def test_extract_dims_list():
    dim = [[32, 64], None, [16, 8], None]
    raw, d1, d2 = DataGenerator._extract_dims(dim, i=0)
    assert raw == [32, 64] and d1 == 32 and d2 == 64
    raw, d1, d2 = DataGenerator._extract_dims(dim, i=1)
    assert raw == [16, 8] and d1 == 16 and d2 == 8


def test_extract_dims_single_element_list():
    dim = [[64], None]
    raw, d1, d2 = DataGenerator._extract_dims(dim, i=0)
    assert raw == [64] and d1 == 64 and d2 == 1


# ═══════════════════════════════════════════════════════════════════════════
# 2.  Format correctness tests — structural validation with native libraries
# ═══════════════════════════════════════════════════════════════════════════

_BASE_OVERRIDES = [
    "++workload.framework=tensorflow",
    "++workload.reader.data_loader=tensorflow",
    "++workload.workflow.train=False",
    "++workload.workflow.generate_data=True",
    "++workload.dataset.num_samples_per_file=8",
    "++workload.dataset.record_length=256",
]


@pytest.mark.timeout(TEST_TIMEOUT_SECONDS, method="thread")
def test_npy_format_correctness():
    """NPY: loadable, correct shape (H x W x N), correct dtype, samples are unique."""
    import numpy as np
    init()
    clean()
    with initialize_config_dir(version_base=None, config_dir=config_dir):
        cfg = compose(config_name="config", overrides=_BASE_OVERRIDES + [
            "++workload.dataset.format=npy",
            "++workload.dataset.num_files_train=4",
            "++workload.dataset.num_files_eval=2",
        ])
        run_benchmark(cfg, verify=False)

        if comm.rank == 0:
            train, _ = _find_files(cfg, None, "npy")
            assert len(train) == 4, f"Expected 4 NPY train files, got {len(train)}"
            for p in train:
                arr = np.load(str(p))
                # NPY reader does: arr[..., sample_index] → last dim is sample
                assert arr.ndim >= 2, f"{p.name}: expected at least 2 dims, got {arr.ndim}"
                num_samples = arr.shape[-1]
                assert num_samples == 8, (
                    f"{p.name}: last dim (num_samples) = {num_samples}, expected 8")
                # Each sample must be unique — not tiled from a single record
                s0 = arr[..., 0].ravel()
                s1 = arr[..., 1].ravel()
                assert not np.array_equal(s0, s1), (
                    f"{p.name}: sample 0 == sample 1 — generator tiled data (identical samples bug)")
    clean()
    finalize()


@pytest.mark.timeout(TEST_TIMEOUT_SECONDS, method="thread")
def test_npz_format_correctness():
    """NPZ: correct \'x\' and \'y\' keys, correct array shape, samples unique."""
    init()
    clean()
    with initialize_config_dir(version_base=None, config_dir=config_dir):
        cfg = compose(config_name="config", overrides=_BASE_OVERRIDES + [
            "++workload.dataset.format=npz",
            "++workload.dataset.num_files_train=4",
            "++workload.dataset.num_files_eval=2",
        ])
        run_benchmark(cfg, verify=False)

        if comm.rank == 0:
            train, _ = _find_files(cfg, None, "npz")
            assert len(train) == 4, f"Expected 4 NPZ train files, got {len(train)}"
            for p in train:
                data = np.load(str(p), allow_pickle=False)
                assert "x" in data.files, (
                    f"{p.name}: missing 'x' key (NPZ reader reads data['x'])")
                assert "y" in data.files, (
                    f"{p.name}: missing 'y' key (labels)")
                arr = data["x"]
                assert arr.ndim >= 2, f"{p.name}: 'x' has {arr.ndim} dims, expected ≥2"
                num_samples = arr.shape[-1]
                assert num_samples == 8, (
                    f"{p.name}: 'x' last dim = {num_samples}, expected 8")
                s0 = arr[..., 0].ravel()
                s1 = arr[..., 1].ravel()
                assert not np.array_equal(s0, s1), (
                    f"{p.name}: NPZ sample 0 == sample 1 — identical samples bug")
    clean()
    finalize()


@pytest.mark.timeout(TEST_TIMEOUT_SECONDS, method="thread")
def test_csv_format_correctness():
    """CSV: readable with pandas, correct row count, rows are NOT all identical."""
    import pandas as pd
    init()
    clean()
    num_samples = 8
    with initialize_config_dir(version_base=None, config_dir=config_dir):
        cfg = compose(config_name="config", overrides=_BASE_OVERRIDES + [
            "++workload.dataset.format=csv",
            "++workload.dataset.num_files_train=4",
            "++workload.dataset.num_files_eval=2",
            f"++workload.dataset.num_samples_per_file={num_samples}",
        ])
        run_benchmark(cfg, verify=False)

        if comm.rank == 0:
            train, _ = _find_files(cfg, None, "csv")
            assert len(train) == 4, f"Expected 4 CSV train files, got {len(train)}"
            for p in train:
                df = pd.read_csv(str(p), header=None)
                assert len(df) == num_samples, (
                    f"{p.name}: row count = {len(df)}, expected {num_samples}")
                # At least one pair of rows must differ — if all rows are the same
                # the generator tiled a single record (identical-samples bug).
                row0 = df.iloc[0].values
                row1 = df.iloc[1].values
                assert not np.array_equal(row0, row1), (
                    f"{p.name}: row 0 == row 1 — CSV identical-samples bug not fixed")
    clean()
    finalize()


@pytest.mark.timeout(TEST_TIMEOUT_SECONDS, method="thread")
def test_parquet_format_correctness():
    """Parquet: readable with pyarrow, correct schema, row count, unique rows."""
    import pyarrow.parquet as pq
    init()
    clean()
    num_samples = 8
    with initialize_config_dir(version_base=None, config_dir=config_dir):
        cfg = compose(config_name="config", overrides=_BASE_OVERRIDES + [
            "++workload.dataset.format=parquet",
            "++workload.dataset.num_files_train=4",
            "++workload.dataset.num_files_eval=2",
            f"++workload.dataset.num_samples_per_file={num_samples}",
        ])
        run_benchmark(cfg, verify=False)

        if comm.rank == 0:
            train, _ = _find_files(cfg, None, "parquet")
            assert len(train) == 4, f"Expected 4 Parquet train files, got {len(train)}"
            for p in train:
                table = pq.read_table(str(p))
                assert table.num_rows == num_samples, (
                    f"{p.name}: row count = {table.num_rows}, expected {num_samples}")
                assert "data" in table.column_names, (
                    f"{p.name}: missing 'data' column in schema {table.column_names}")
                # Rows must not all be identical
                col = table.column("data")
                row0 = col[0].as_py()
                row1 = col[1].as_py()
                assert row0 != row1, (
                    f"{p.name}: row 0 == row 1 — parquet identical-samples bug not fixed")
    clean()
    finalize()


@pytest.mark.timeout(TEST_TIMEOUT_SECONDS, method="thread")
def test_hdf5_format_correctness():
    """HDF5: readable with h5py, correct datasets, correct shape, samples unique."""
    import h5py
    init()
    clean()
    num_samples = 8
    with initialize_config_dir(version_base=None, config_dir=config_dir):
        cfg = compose(config_name="config", overrides=_BASE_OVERRIDES + [
            "++workload.dataset.format=hdf5",
            "++workload.dataset.num_files_train=4",
            "++workload.dataset.num_files_eval=2",
            f"++workload.dataset.num_samples_per_file={num_samples}",
        ])
        run_benchmark(cfg, verify=False)

        if comm.rank == 0:
            train, _ = _find_files(cfg, None, "hdf5")
            assert len(train) == 4, f"Expected 4 HDF5 train files, got {len(train)}"
            for p in train:
                with h5py.File(str(p), "r") as hf:
                    assert "records_0" in hf, (
                        f"{p.name}: missing 'records_0' dataset (keys: {list(hf.keys())})")
                    assert "labels" in hf, (
                        f"{p.name}: missing 'labels' dataset")
                    ds = hf["records_0"]
                    # HDF5 reader accesses ds[sample_index] → first dim is sample
                    assert ds.shape[0] == num_samples, (
                        f"{p.name}: records_0 shape[0] = {ds.shape[0]}, expected {num_samples}")
                    s0 = ds[0].ravel()
                    s1 = ds[1].ravel()
                    assert not np.array_equal(s0, s1), (
                        f"{p.name}: HDF5 sample 0 == sample 1 — identical samples")
    clean()
    finalize()


@pytest.mark.timeout(TEST_TIMEOUT_SECONDS, method="thread")
def test_tfrecord_format_correctness():
    """TFRecord: parseable with tf.data, correct feature keys, records are unique."""
    import tensorflow as tf
    init()
    clean()
    num_samples = 4
    with initialize_config_dir(version_base=None, config_dir=config_dir):
        cfg = compose(config_name="config", overrides=_BASE_OVERRIDES + [
            "++workload.dataset.format=tfrecord",
            "++workload.dataset.num_files_train=4",
            "++workload.dataset.num_files_eval=2",
            f"++workload.dataset.num_samples_per_file={num_samples}",
        ])
        run_benchmark(cfg, verify=False)

        if comm.rank == 0:
            train, _ = _find_files(cfg, None, "tfrecord")
            assert len(train) == 4, f"Expected 4 TFRecord train files, got {len(train)}"
            for p in train:
                dataset = tf.data.TFRecordDataset(str(p))
                records = list(dataset.take(num_samples))
                assert len(records) == num_samples, (
                    f"{p.name}: read {len(records)} records, expected {num_samples}")
                # Parse the first two and verify they contain the expected features
                for raw in records[:2]:
                    example = tf.train.Example()
                    example.ParseFromString(raw.numpy())
                    feats = example.features.feature
                    assert "image" in feats, (
                        f"{p.name}: TFRecord record missing 'image' feature")
                    assert "size" in feats, (
                        f"{p.name}: TFRecord record missing 'size' feature")
                    img_bytes = feats["image"].bytes_list.value[0]
                    assert len(img_bytes) > 0, (
                        f"{p.name}: 'image' feature is empty")
                # Records must not all be identical bytes
                r0 = records[0].numpy()
                r1 = records[1].numpy()
                assert r0 != r1, (
                    f"{p.name}: TFRecord records 0 and 1 are identical — "
                    "identical-samples bug in TFRecord generator")
    clean()
    finalize()


# ═══════════════════════════════════════════════════════════════════════════
# 3.  Cross-file uniqueness — every generated file must contain distinct data
# ═══════════════════════════════════════════════════════════════════════════

@pytest.mark.timeout(TEST_TIMEOUT_SECONDS, method="thread")
def test_cross_file_data_uniqueness():
    """All NPY files generated in one run must have different SHA-256 hashes.

    This validates that the RNG state advances between files so that no two
    files contain the same data.  If all files share a seed this test fails.
    """
    init()
    clean()
    with initialize_config_dir(version_base=None, config_dir=config_dir):
        cfg = compose(config_name="config", overrides=_BASE_OVERRIDES + [
            "++workload.dataset.format=npy",
            "++workload.dataset.num_files_train=6",
            "++workload.dataset.num_files_eval=0",
            "++workload.dataset.num_samples_per_file=4",
            "++workload.dataset.record_length=1024",
        ])
        run_benchmark(cfg, verify=False)

        if comm.rank == 0:
            train, _ = _find_files(cfg, None, "npy")
            assert len(train) == 6, f"Expected 6 NPY files, got {len(train)}"
            hashes = [_sha256(str(p)) for p in train]
            unique_hashes = set(hashes)
            assert len(unique_hashes) == len(hashes), (
                f"Only {len(unique_hashes)} unique hashes for {len(hashes)} files — "
                "some files contain identical data.  RNG is likely being reset to the "
                "same seed between files.")
    clean()
    finalize()


@pytest.mark.timeout(TEST_TIMEOUT_SECONDS, method="thread")
def test_parquet_cross_file_uniqueness():
    """All Parquet files must have different content (SHA-256 hashes differ)."""
    import pyarrow.parquet as pq
    init()
    clean()
    with initialize_config_dir(version_base=None, config_dir=config_dir):
        cfg = compose(config_name="config", overrides=_BASE_OVERRIDES + [
            "++workload.dataset.format=parquet",
            "++workload.dataset.num_files_train=6",
            "++workload.dataset.num_files_eval=0",
            "++workload.dataset.num_samples_per_file=8",
        ])
        run_benchmark(cfg, verify=False)

        if comm.rank == 0:
            train, _ = _find_files(cfg, None, "parquet")
            assert len(train) == 6
            # Compare the first-row \'data\' column across files
            first_rows = []
            for p in train:
                table = pq.read_table(str(p))
                first_rows.append(table.column("data")[0].as_py())
            unique = set(tuple(r) if isinstance(r, list) else r for r in first_rows)
            assert len(unique) == len(first_rows), (
                f"Only {len(unique)} unique first rows — parquet files share data")
    clean()
    finalize()


# ═══════════════════════════════════════════════════════════════════════════
# 4.  Reader compatibility — DLIO readers can open generator output
# ═══════════════════════════════════════════════════════════════════════════

@pytest.mark.timeout(TEST_TIMEOUT_SECONDS, method="thread")
def test_npy_reader_compatibility():
    """NPY files must be openable by the NPYReader and yield correct samples."""
    from dlio_benchmark.reader.npy_reader import NPYReader
    from dlio_benchmark.common.enumerations import DatasetType
    init()
    clean()
    with initialize_config_dir(version_base=None, config_dir=config_dir):
        cfg = compose(config_name="config", overrides=_BASE_OVERRIDES + [
            "++workload.dataset.format=npy",
            "++workload.dataset.num_files_train=4",
            "++workload.dataset.num_files_eval=0",
            "++workload.dataset.num_samples_per_file=8",
        ])
        run_benchmark(cfg, verify=False)

        if comm.rank == 0:
            train, _ = _find_files(cfg, None, "npy")
            workload_dict = OmegaConf.to_container(cfg["workload"], resolve=True)
            workload_dict.setdefault("output", {})["folder"] = DLIO_TEST_OUTPUT_DIR
            ConfigArguments.reset()
            args = ConfigArguments.get_instance()
            args.derive_configurations(workload_dict)

            reader = NPYReader(DatasetType.TRAIN, thread_index=0, epoch=1)
            for p in train[:2]:
                # NPYReader uses _LocalFSIterableMixin: open() returns a cached
                # byte count (int), not a decoded array. Decoding is skipped
                # because only raw storage bandwidth matters for benchmarking.
                # The cache is populated by _localfs_prefetch_all() inside next();
                # calling open() directly (outside next()) returns the default 0.
                result = reader.open(str(p))
                assert isinstance(result, int), (
                    f"NPYReader.open() should return int byte count, got "
                    f"{type(result).__name__}"
                )
                # Verify the generated file is a valid numpy array via np.load.
                arr = np.load(str(p))
                assert arr.ndim >= 2, f"Generated NPY has unexpected shape {arr.shape}"

    clean()
    finalize()


@pytest.mark.timeout(TEST_TIMEOUT_SECONDS, method="thread")
def test_npz_reader_compatibility():
    """NPZ files must be openable by NPZReader and return an array with key \'x\'."""
    from dlio_benchmark.reader.npz_reader import NPZReader
    from dlio_benchmark.common.enumerations import DatasetType
    init()
    clean()
    with initialize_config_dir(version_base=None, config_dir=config_dir):
        cfg = compose(config_name="config", overrides=_BASE_OVERRIDES + [
            "++workload.dataset.format=npz",
            "++workload.dataset.num_files_train=4",
            "++workload.dataset.num_files_eval=0",
            "++workload.dataset.num_samples_per_file=8",
        ])
        run_benchmark(cfg, verify=False)

        if comm.rank == 0:
            train, _ = _find_files(cfg, None, "npz")
            workload_dict = OmegaConf.to_container(cfg["workload"], resolve=True)
            workload_dict.setdefault("output", {})["folder"] = DLIO_TEST_OUTPUT_DIR
            ConfigArguments.reset()
            args = ConfigArguments.get_instance()
            args.derive_configurations(workload_dict)

            reader = NPZReader(DatasetType.TRAIN, thread_index=0, epoch=1)
            for p in train[:2]:
                arr = reader.open(str(p))
                assert arr is not None, f"NPZReader.open() returned None for {p.name}"
    clean()
    finalize()


@pytest.mark.timeout(TEST_TIMEOUT_SECONDS, method="thread")
def test_parquet_reader_compatibility():
    """Parquet files must be openable by ParquetReader without errors."""
    import pyarrow.parquet as pq
    init()
    clean()
    with initialize_config_dir(version_base=None, config_dir=config_dir):
        cfg = compose(config_name="config", overrides=_BASE_OVERRIDES + [
            "++workload.dataset.format=parquet",
            "++workload.dataset.num_files_train=4",
            "++workload.dataset.num_files_eval=0",
            "++workload.dataset.num_samples_per_file=8",
        ])
        run_benchmark(cfg, verify=False)

        if comm.rank == 0:
            train, _ = _find_files(cfg, None, "parquet")
            for p in train[:2]:
                # Use pyarrow directly — same as what ParquetReader does internally.
                pf = pq.ParquetFile(str(p))
                assert pf.metadata.num_rows == 8, (
                    f"{p.name}: metadata.num_rows = {pf.metadata.num_rows}, expected 8")
                table = pf.read()
                assert table.num_rows == 8
    clean()
    finalize()


# ═══════════════════════════════════════════════════════════════════════════
# 5.  Reproducibility — same config produces bit-identical files across runs
# ═══════════════════════════════════════════════════════════════════════════

@pytest.mark.timeout(TEST_TIMEOUT_SECONDS * 2, method="thread")
def test_npy_reproducibility():
    """NPY generator must produce bit-identical files on two consecutive runs."""
    init()
    clean()

    overrides = _BASE_OVERRIDES + [
        "++workload.dataset.format=npy",
        "++workload.dataset.num_files_train=4",
        "++workload.dataset.num_files_eval=2",
        "++workload.dataset.num_samples_per_file=4",
        "++workload.dataset.record_length=1024",
    ]

    hashes_run1 = {}
    with initialize_config_dir(version_base=None, config_dir=config_dir):
        cfg = compose(config_name="config", overrides=overrides)
        run_benchmark(cfg, verify=False)
        if comm.rank == 0:
            data_folder = cfg.workload.dataset.data_folder
            for split in ("train", "valid"):
                for p in sorted(pathlib.Path(f"{data_folder}/{split}").rglob("*.npy")):
                    hashes_run1[f"{split}/{p.name}"] = _sha256(str(p))

    comm.Barrier()
    if comm.rank == 0:
        shutil.rmtree("./data/", ignore_errors=True)
    comm.Barrier()

    hashes_run2 = {}
    with initialize_config_dir(version_base=None, config_dir=config_dir):
        cfg2 = compose(config_name="config", overrides=overrides)
        run_benchmark(cfg2, verify=False)
        if comm.rank == 0:
            data_folder2 = cfg2.workload.dataset.data_folder
            for split in ("train", "valid"):
                for p in sorted(pathlib.Path(f"{data_folder2}/{split}").rglob("*.npy")):
                    hashes_run2[f"{split}/{p.name}"] = _sha256(str(p))

    if comm.rank == 0:
        assert hashes_run1 == hashes_run2, (
            "NPY generator is NOT reproducible across runs.\n"
            f"Run 1 hashes: {hashes_run1}\n"
            f"Run 2 hashes: {hashes_run2}")

    clean()
    finalize()
